import type { Metadata } from "next";
import { Header, Sidebar } from "@/components/base";
import { ToastContainer } from "react-toastify";
import "@/styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="fixed left-0 top-0">
          <Sidebar />
        </div>
        <div className="fixed z-50 top-2 left-[17.3rem]">
          <Header/>
        </div>
        <div className="font-poppins h-screen w-full">{children}</div>

        <ToastContainer />
      </body>
    </html>
  );
}
